### PR TITLE
refactor: components and modules for ui app

### PR DESCRIPTION
**Pull request by vik-13**
- move html and scss to separated files;
 - create modules for each component instead of declaration all components inside AppModule;
 - update some global events;
 - clean up the code a bit;
 
 p.s. I hope you won't update whole project again :)

### CODE REVIEW

**Comment by mgechev** [comment]
Good job! There are some merge conflicts. Once you resolve them and update the commit messages we can merge.

**Comment by vik-13** [comment]
> Good job! There are some merge conflicts. Once you resolve them and update the commit messages we can merge.

Thanks! I will fix it in a moment. Also it would be great to know some roadmap if you have or maybe some your ideas?

I'm still thinking about what exactly would be really helpful with refactoring huge projects. What's kind of info it would be useful to show.

**Comment by vik-13** [comment]
Updated last commit message. Or should I update previous ones as well? For next changes I'm gonna create smaller commits to make it more consistent.

**Comment by mgechev** [comment]
>I'm still thinking about what exactly would be really helpful with refactoring huge projects. What's kind of info it would be useful to show.

Currently, there are a few features missing or buggy compared to the previous version:
- There's no template exploration. This should be relatively straightforward but would require changes in ngast
- The `CMD+P` fuzzy search is a little buggy. When you start typing a name and press "Enter" the list updates and you navigate to the wrong item
- We could improve the top menu. For example, when you press "CMD+M" to show modules, we could show a tick in the menu item to indicate this option is active.
- There's a bug in the metadata table at the bottom-right. When you select certain boxes the metadata does not show up.
- There's missing metadata. For example, right now we're not showing if a pipe is pure.
- etc.

If you have feature request ideas, we can discuss them in an issue.

**Review by mgechev — APPROVED** [review]
LGTM. We don't necessarily have to have a single module per component because this will just introduce extra boilerplate without bringing much value. Code splitting is not critical for an Electron app.

**Pull request merged**
